from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODEL_CATALOG = ROOT / "models" / "model_catalog.json"


def model_repo(model_id_or_repo: str) -> str:
    catalog = json.loads(MODEL_CATALOG.read_text(encoding="utf-8"))
    for item in catalog.get("models", []):
        if item["id"] == model_id_or_repo:
            return item["repo"]
    return model_id_or_repo


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate an Axolotl QLoRA config for a coding SFT run.")
    parser.add_argument("--model", default="qwen2_5_coder_32b", help="Model id from model_catalog.json or HF repo")
    parser.add_argument("--dataset", default="pc_train/data/merged_code_sft.jsonl")
    parser.add_argument("--out", default="pc_train/configs/axolotl_qlora.yaml")
    parser.add_argument("--output-dir", default="pc_train/outputs/qlora_run")
    parser.add_argument("--sequence-len", type=int, default=8192)
    parser.add_argument("--micro-batch-size", type=int, default=1)
    parser.add_argument("--grad-accum", type=int, default=8)
    parser.add_argument("--epochs", type=float, default=1.0)
    parser.add_argument("--learning-rate", default="2e-5")
    parser.add_argument("--lora-r", type=int, default=64)
    parser.add_argument("--lora-alpha", type=int, default=128)
    args = parser.parse_args()

    repo = model_repo(args.model)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = f"""# Generated by pc_train/scripts/make_axolotl_config.py
# Install: pip install -r pc_train/requirements-pc-train.txt
# Run:     accelerate launch -m axolotl.cli.train {out.as_posix()}

base_model: {repo}
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

load_in_4bit: true
strict: false

datasets:
  - path: {args.dataset}
    type: chat_template
    field_messages: messages

dataset_prepared_path: pc_train/cache/prepared
output_dir: {args.output_dir}

sequence_len: {args.sequence_len}
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

adapter: qlora
lora_model_dir:
lora_r: {args.lora_r}
lora_alpha: {args.lora_alpha}
lora_dropout: 0.05
lora_target_linear: true

wandb_project:
wandb_entity:
wandb_name:

gradient_accumulation_steps: {args.grad_accum}
micro_batch_size: {args.micro_batch_size}
num_epochs: {args.epochs}
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: {args.learning_rate}
warmup_ratio: 0.03
weight_decay: 0.0
max_grad_norm: 1.0

bf16: auto
tf32: true
flash_attention: true

logging_steps: 10
saves_per_epoch: 2
evals_per_epoch: 2
val_set_size: 0.02
save_total_limit: 3

special_tokens:
  pad_token: <|endoftext|>
"""
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
